# Generated by Django 3.2 on 2021-05-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210504_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='audience_score',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
