# Generated by Django 3.2 on 2021-05-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_audience_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratereview',
            old_name='rewiew',
            new_name='review',
        ),
    ]
