# Generated by Django 3.2 on 2021-05-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_rename_rewiew_ratereview_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratereview',
            name='review',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
